const CarouselActionTypes={
    //To Add All Files After selecting category
    ADD_ALL_FILES_START:'ADD_ALL_FILES_START',
    ADD_ALL_FILES_SUCCESS:'ADD_ALL_FILES_SUCCESS',
    ADD_ALL_FILES_FAILURE:'ADD_ALL_FILES_FAILURE',

    //To Add Single Files After Drag
    ADD_SINGLE_FILE_START:'ADD_SINGLE_FILE_START',
    ADD_SINGLE_FILE_SUCCESS:'ADD_SINGLE_FILE_SUCCESS',
    ADD_SINGLE_FILE_FAILURE:'ADD_SINGLE_FILE_FAILURE',

    //To Remove Single Files After Drag
    REMOVE_SINGLE_FILE_START:'REMOVE_SINGLE_FILE_START',
    REMOVE_SINGLE_FILE_SUCCESS:'REMOVE_SINGLE_FILE_SUCCESS',
    REMOVE_SINGLE_FILE_FAILURE:'REMOVE_SINGLE_FILE_FAILURE',

    //To Track Selected Carousel
    SELECT_CAROUSEL_INDEX_START:'SELECT_CAROUSEL_INDEX_START',
    SELECT_CAROUSEL_INDEX_SUCCESS:'SELECT_CAROUSEL_INDEX_SUCCESS',
    SELECT_CAROUSEL_INDEX_FAILURE:'SELECT_CAROUSEL_INDEX_FAILURE',

};
export default CarouselActionTypes;